spring:
  cloud:
    gateway:
      routes:
        - id: short-url-admin-aggregation
          uri: lb://short-url-aggregation/short-url/admin/**
          predicates:
            - Path=/short-url/admin/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /short-url/admin/v1/user/login
                  - /short-url/admin/v1/user/has-username

        - id: short-url-project-aggregation
          uri: lb://short-url-aggregation/short-url/**
          predicates:
            - Path=/short-url/**
          filters:
            - name: TokenValidate
