server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    active: aggregation
    # active: dev
  data:
    redis:
      host: 192.168.200.131
      port: 6380
      password: zzn199636520
#      host: 127.0.0.1
#      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
