spring:
  cloud:
    gateway:
      routes:
        - id: short-url-admin
          uri: lb://short-url-admin/short-url/admin/**
          predicates:
            - Path=/short-url/admin/**
          filters:
            - name: TokenValidate
              args:
                whitePathList: #白名单
                  - /short-url/admin/v1/user/login
                  - /short-url/admin/v1/user/has-username

        - id: short-url-project
          uri: lb://short-url-project/short-url/**
          predicates:
            - Path=/short-url/**
          filters:
            - name: TokenValidate
