server:
  port: 8002

spring:
  application:
    name: short-url-admin
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 192.168.200.131
      port: 6380
      password: zzn199636520
#      host: 127.0.0.1
#      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

short-url:
  group:
    max-count: 20
  flow-limit:
    enable: true
    time-window: 1 #风控的时间
    max-access-count: 20 #风控时间内允许调用的API次数
