server:
  port: 8003

spring:
  application:
    name: short-link-aggregation
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 192.168.200.131
      port: 6380
      password: zzn199636520
#      host: 127.0.0.1
#      port: 6379
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

aggregation:
  remote-url: http://127.0.0.1:${server.port}

short-link:
  group:
    max-count: 20
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20
  domain:
    default: zhaozn:8003
  stats:
    locale:
      amap-key: 824c511f0997586ea016f979fdb23087

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml


rocketmq:
  name-server: 192.168.200.131:9876
#  name-server: 127.0.0.1:9876
  producer:
    group: short-link_project-service_stats-save_pg
    topic: short-link_project-service_topic
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  consumer:
    group: short-link_project-service_stats-save_cg